# Devcontainer validation jobs

devcontainer:validate:
  image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim@sha256:531f855bda2c73cd6ef67d56b733b357cea384185b3022bd09f05e002cd144ca
  stage: lint
  rules:
    - changes:
        compare_to: "refs/heads/$CI_DEFAULT_BRANCH"
        paths:
          - ".devcontainer/*"
          - ".gitlab/ci/devcontainer.gitlab-ci.yml"
      if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - changes:
        paths:
          - ".devcontainer/*"
          - ".gitlab/ci/devcontainer.gitlab-ci.yml"
      if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
  script:
    - uvx check-jsonschema --schemafile "https://raw.githubusercontent.com/devcontainers/spec/main/schemas/devContainer.schema.json" .devcontainer/devcontainer.json
  interruptible: true

devcontainer:build:
  extends: .docker-in-docker
  stage: build
  rules:
    - changes:
        compare_to: "refs/heads/$CI_DEFAULT_BRANCH"
        paths:
          - ".devcontainer/*"
          - ".gitlab/ci/devcontainer.gitlab-ci.yml"
      if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - changes:
        paths:
          - ".devcontainer/*"
          - ".gitlab/ci/devcontainer.gitlab-ci.yml"
      if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
  script:
    - docker build .devcontainer/
  interruptible: true
